#!/usr/bin/env bash
#
# Bash script for provisioning the MongoDB instances

set -e
set -x

function config(){
  export CLIENT_IP_ADDR=`ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}' | tail -1`
  export CLIENT_FQDN=`hostname`
  export CLIENT_NAME=`hostname | cut -d. -f 1 | tr '[:upper:]' '[:lower:]'`
  echo "Configuring /etc/hosts ..."
  echo "127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4" > /etc/hosts
  echo "::1       localhost localhost.localdomain localhost6 localhost6.localdomain6" >> /etc/hosts
  echo "$CLIENT_IP_ADDR    $CLIENT_FQDN $CLIENT_NAME" >> /etc/hosts
}

function install_mongod(){
  echo "Install MongoDB Enterprise"
  wget -q -O mongodb-linux-x86_64-enterprise-ubuntu1404-3.4.0.tgz https://downloads.mongodb.com/linux/mongodb-linux-x86_64-enterprise-ubuntu1404-3.4.0.tgz?jmp=university
  tar xvf mongodb-linux-x86_64-enterprise-ubuntu1404-3.4.0.tgz
  sudo mv -f mongodb-linux-x86_64-enterprise-ubuntu1404-3.4.0/bin/* /usr/bin
  rm -r mongodb-linux-x86_64-enterprise-ubuntu1404-3.4.0/
  rm mongodb-linux-x86_64-enterprise-ubuntu1404-3.4.0.tgz

  sudo sh -c "killall mongod; true"
  sudo mkdir -p /data
  sudo chmod -R 777 /data
  mkdir -p /data/db
  mkdir -p /home/vagrant/data
  chmod -R 777 /home/vagrant/data
  chown -R vagrant:vagrant /home/vagrant/data
  mkdir -p /home/vagrant/data/authdb
  echo "Set LC_ALL=C to .profile"
  sudo echo "export LC_ALL=C" >> /home/vagrant/.profile
}

function update_repo(){
  echo "Install MongoDB Enterprise Repository"
  echo "deb http://repo.mongodb.com/apt/ubuntu "$(lsb_release -sc)"/mongodb-enterprise/3.3 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-enterprise.list
  sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
  echo "Update Repositoryies"
  sudo apt-get update -y
  echo "Installing MongoDB Enterprise Dependencies"
  sudo apt-get install -y libgssapi-krb5-2 libsasl2-2 libssl1.0.0 libstdc++6 snmp
}


function config(){
  sudo su
  # disable THP
  echo -e "never" > /sys/kernel/mm/transparent_hugepage/enabled
  echo -e "never" > /sys/kernel/mm/transparent_hugepage/defrag
  # disable mongod upstart service
  echo 'manual' | sudo tee /etc/init/mongod.override
}


function install_mongosqld() {
  echo "Installing BI Connector"
  mkdir -p /home/vagrant/biconnector
  curl -o mongo-bi.tgz https://s3.amazonaws.com/mciuploads/sqlproxy/binaries/linux/mongodb-bi-linux-x86_64-ubuntu1404-v2.0.0-beta5-7-g048ac56.tgz
  tar xf mongo-bi.tgz -C /home/vagrant/biconnector
  sudo ln -s /home/vagrant/biconnector/bin/* /usr/local/bin
  rm mongo-bi.tgz
  echo "Done: Installing BI Connector"
}

function download_dataset() {
  echo "Download Dataset"
  curl -o dataset.tgz https://s3.amazonaws.com/m034/biconnector/dataset.tgz
  tar xf dataset.tgz  -C /dataset
  echo "Done: Download Dataset"
}

function install_mysqlclient() {
  echo "Install MySQL client"
  sudo apt-get install mysql-client -y --force-yes
  echo "Done: Install MySQL client"
}

function data_path() {
  sudo mkdir -p /data
  sudo chown -R vagrant:vagrant /data
}

config
update_repo
install_mongod
install_mongosqld
install_mysqlclient
download_dataset
data_path
echo "DONE"
