#!/usr/bin/env bash
#
# Bash script for provisioning the MongoDB instances

set -e
set -x

function config_network(){
  sudo su
  export CLIENT_IP_ADDR=`ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}' | tail -1`
  export CLIENT_FQDN=`hostname`
  export CLIENT_NAME=`hostname | cut -d. -f 1 | tr '[:upper:]' '[:lower:]'`
  echo "Configuring /etc/hosts ..."
  echo "127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4" > /etc/hosts
  echo "::1       localhost localhost.localdomain localhost6 localhost6.localdomain6" >> /etc/hosts
  echo "192.168.15.101  m1.university.mongodb   m1" >> /etc/hosts
  echo "192.168.15.102  m2.university.mongodb   m2" >> /etc/hosts
  echo "192.168.15.103  m3.university.mongodb   m3" >> /etc/hosts
  echo "$CLIENT_IP_ADDR    $CLIENT_FQDN $CLIENT_NAME" >> /etc/hosts
}

function install_mongod(){
  echo "Install MongoDB Enterprise"
  wget -q -O mongodb-linux-x86_64-enterprise-ubuntu1404-3.4.2.tgz https://downloads.mongodb.com/linux/mongodb-linux-x86_64-enterprise-ubuntu1404-3.4.2.tgz?jmp=university
  tar xvf mongodb-linux-x86_64-enterprise-ubuntu1404-3.4.2.tgz
  sudo mv -f mongodb-linux-x86_64-enterprise-ubuntu1404-3.4.2/bin/* /usr/bin
  rm -r mongodb-linux-x86_64-enterprise-ubuntu1404-3.4.2/
  rm mongodb-linux-x86_64-enterprise-ubuntu1404-3.4.2.tgz

  sudo sh -c "killall mongod; true"
  sudo mkdir -p /data
  sudo chmod -R 777 /data
  mkdir -p /data/db
  mkdir -p /home/vagrant/data
  chmod -R 777 /home/vagrant/data
  chown -R vagrant:vagrant /home/vagrant/data
  echo "Set LC_ALL=C to .profile"
  sudo echo "export LC_ALL=C" >> /home/vagrant/.profile
}

function install_mtools(){
    sudo apt-get install -y python-dev
    sudo apt-get install -y python-pip
    sudo pip install psutil
    sudo pip install mtools
    sudo pip install pymongo
}

function install_mplotqueries_dependencies(){
    sudo apt-get install -y libfreetype6-dev
    sudo apt-get install -y libxft-dev
    sudo pip install mplotqueries
}

function update_repo(){
  echo "Install MongoDB Enterprise Repository"
  echo "deb http://repo.mongodb.com/apt/ubuntu "$(lsb_release -sc)"/mongodb-enterprise/3.3 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-enterprise.list
  sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
  echo "Update Repositoryies"
  sudo apt-get update -y
  echo "Installing MongoDB Enterprise Dependencies"
  sudo apt-get install -y libgssapi-krb5-2 libsasl2-2 libssl1.0.0 libstdc++6 snmp
}


function config(){
  sudo su
  # disable THP
  echo -e "never" > /sys/kernel/mm/transparent_hugepage/enabled
  echo -e "never" > /sys/kernel/mm/transparent_hugepage/defrag
  # disable mongod upstart service
  echo 'manual' | sudo tee /etc/init/mongod.override
}


config
config_network
update_repo
install_mongod
install_mtools
# Uncomment the following line and mplotqueries will work. Takes a long time, and doesn't benefit you much on a headless VM.
# install_mplotqueries_dependencies
echo "DONE"
