if Vagrant::VERSION < "2.0.0"
  $stderr.puts "Must redirect to new repository for old Vagrant versions"
  Vagrant::DEFAULT_SERVER_URL.replace('https://vagrantcloud.com')
end

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false
  config.vm.synced_folder "shared/", "/shared", create: true

  (1..3).each do |i|
    config.vm.define "m#{i}" do |server|
      server.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--cpus", "2"]
        vb.name = "m#{i}"
        vb.memory = 1024
      end
      server.vm.hostname = "m#{i}.mongodb.university"
      server.vm.network :private_network, ip: "192.168.15.10#{i}"
      server.vm.provision :shell, path: "provision", args: ENV['ARGS']
    end
  end
end
