#!/usr/bin/env bash

set -e
set -x

kdcPassword="kdcpassword123"

function config_hosts(){
  echo "Configuring /etc/hosts..."
  echo "192.168.31.100 database.m310.mongodb.university database"   >> /etc/hosts
  echo "192.168.31.200 infrastructure.m310.mongodb.university infrastructure"   >> /etc/hosts
  yum install -y net-tools
  ifconfig eth1 192.168.31.200 up
}

function install_kerberos(){
  echo "Installing Kerberos..."
  yum install -y krb5-server krb5-server-ldap krb5-libs krb5-workstation
}

function config_kerberos(){
  echo "Configuring Kerberos..."

  # Configure KDC
  sed -i 's/EXAMPLE/MONGODB.UNIVERSITY/g' /var/kerberos/krb5kdc/kdc.conf
  sed -i 's/EXAMPLE/MONGODB.UNIVERSITY/g' /var/kerberos/krb5kdc/kadm5.acl
  cp /vagrant/shared/krb5.conf /etc/

  # Add entropy because we're in a VM
  yum install rng-tools -y
  rngd -r /dev/urandom -o /dev/random -b

  # Create a new KDC database
  kdb5_util create -s -P $kdcPassword

  # Start Kerberos
  service krb5kdc start
  service kadmin start
  chkconfig krb5kdc on
  chkconfig kadmin on

  # Add principal for mongod
  kadmin.local -q "addprinc mongodb/database.m310.mongodb.university" <<!
webscale
webscale
!

  # Create keytab for mongod
  kadmin.local -q "ktadd -k mongodb.keytab mongodb/database.m310.mongodb.university"

  cp mongodb.keytab /home/vagrant/shared
}

function install_ldap(){
  yum -y install openldap-servers openldap-clients openldap-devel openldap \
         python-devel gcc cyrus-sasl-plain xfsprogs net-snmp ps-misc wget curl
  echo "Instal pip"
  curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
  python get-pip.py
  easy_install pip
  pip -V
  pip install python-ldap
  rm get-pip.py
}

#config_hosts
#install_kerberos
#config_kerberos
install_ldap
echo "DONE"
